name: dl2022
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.6
  - pip=22.2.2
  - pytorch-cuda=11.7
  - pytorch=1.13.0
  - torchvision=0.14.0
  - torchaudio=0.13.0
  - pip:
    - nflows==0.12
    - scikit-learn==1.2.2
    - wandb==0.15.0