#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=RunAE_Normalized_Flow_Development
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=00:04:00
#SBATCH --mem=32000M
#SBATCH --output=job_files/train.out

module purge
module load 2021
module load Anaconda3/2021.05

# Your job starts in the directory where you call sbatch
# Activate your environment
source activate dl2022

# Run your code
srun python -u train.py
